### ISSUE TITLE
Async Hangouts Apps Script - user has to auth, leave space, and then return to trigger onAddToSpace(e)

### ISSUE THREAD

**Issue by derrickrc** [gsuitedevs/hangouts-chat-samples#26] opened 2019-04-25 16:40 UTC
I followed the instructions here: https://developers.google.com/hangouts/chat/how-tos/bots-apps-script#async_messages

- When someone else in my organization adds the bot, the user first must chat the bot in order for it to respond and let them know it requires configuration and takes them to the Apps Scripts authorization screen. Afterwards though, the bot does not function as the spaceId is not captured within script properties.

- Only after removing the bot from the space and then re-adding it does it successfully add the spaceId to the App Script project script properties and begin to function.

Am I doing something wrong here or is this expected behavior? Is there some workaround apart from organization-wide delegation that would make this process smoother? Thanks.

**Comment by derrickrc** [comment] 2019-04-25 22:07
Another question - with the sunsetting of Classic Hangouts for gSuite, will Hangouts Chat bots be able to chat with users **through gmail**?

**Comment by sqrrrl** [comment] 2019-04-30 22:19
Looks like that's expected behavior -- there's a small comment at the end of the sample:

"It's possible for a user to add your bot to a space before authorizing your bot. In this case, your bot is unable to respond to the add-to-space event."

That said, it's not very clear in the doc that that comment applies and there should be some better guidance provided. Since that particular sample isn't in this repo and just in the docs, I filed a bug internally against the docs to have that clarified.

Closing this issue here since it doesn't apply to this repo.

**Closed by sqrrrl** 2019-04-30 22:19 UTC
